baseURL = 'https://imomaliev.com'
languageCode = 'en-us'
title = 'Blog'
theme = 'theme'

[caches]
  [caches.images]
    dir = ':cacheDir/images'

[module]
  [[module.mounts]]
    includeFiles = ['[0-9][0-9][0-9][0-9]-*.md']
    source = '../adrs'
    target = 'content/adrs'

  [[module.mounts]]
    source = 'content'
    target = 'content'
