baseURL = 'https://imomaliev.com'
languageCode = 'en-us'
title = 'Blog'

[caches]
  [caches.images]
    dir = ':cacheDir/images'

[module]
  replacements = 'github.com/imomaliev/blog/theme -> ../../theme'

  [[module.imports]]
    path = 'github.com/imomaliev/blog/theme'

  [[module.mounts]]
    includeFiles = ['[0-9][0-9][0-9][0-9]-*.md']
    source = '../adrs'
    target = 'content/adrs'

  [[module.mounts]]
    source = 'content'
    target = 'content'
